---
- name: Upgrade Fedora System
  hosts: localhost
  become: true
  tasks:
    - name: Refresh DNF cache
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
